plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.2.0'
    id("org.jetbrains.kotlinx.kover") version "0.9.9"
}

group = 'com.ingsis.grupo14'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    kover(project(":modules:common"))
    kover(project(":modules:lexer"))
    kover(project(":modules:parser"))
    kover(project(":modules:interpreter"))
}

test {
    useJUnitPlatform()
}
kotlin {
    jvmToolchain(21)
}

kover {
    reports{
        verify {
            rule {
                minBound(80)
            }
        }
    }
}
